version: '3.7'

services:
  web:
    image: django:latest
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
    - "8000:8000"
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: test #  change this 
      SQL_USER: pg_user  # change this 
      SQL_PASSWORD: ######  # change this 
      SQL_HOST: new-database.cj31lrfhhi8s.us-east-1.rds.amazonaws.com # change this 
      SQL_PORT: 5432  # change this 

volumes:
  static_volume:
  media_volume:
